name: GardenBank
main: pers.tany.gardenbank.Main
version: 1.0.0
author: tany
description: 花园银行存款
depend: [ YukiNoaAPI ]
api-version: 1.13
commands:
  GardenBank:
    usage: /GardenBank
    aliases: [ gb ]
permissions:
  gb.gold:
    default: true
  gb.diamond:
    default: true
  gb.pacificoceanoceannd:
    default: true